language: node_js
node_js:
  - node

sudo: required

services:
  - docker

before_install:
  - env | grep -vE "^(PATH=)" > .env
  - docker run -dit -e --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.38.11-64bit bash


script:
  - docker exec -it emscripten bash ./tools/deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "8042239d1efc"
  - COMMIT_AUTHOR_EMAIL: "pierre.benard@laposte.net"